import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { NextAuthSessionProvider } from "@/components/NextAuthSessionProvider/NextAuthSessionProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
        <body className={inter.className}>
          <Toaster />
          {children}
        </body>
      </NextAuthSessionProvider>
    </html>
  );
}
